name: Update Contributions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1' # Every Monday at 06:00 UTC

jobs:
  update-contributions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install requests
        run: pip install requests
      - name: Update README
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: python update_contributions.py
      - name: Commit and Push if Changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update Latest Contributions section [bot]"
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
